# FIXME implement it to current project

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
    networks:
      - ctf-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: prod.dockerfile
    depends_on:
      postgres:
       condition: 'service_healthy'
    networks:
      - ctf-network
    restart: always
      
  postgres:
    image: postgres:15-alpine
    container_name: phishing-postgres
    environment:
      POSTGRES_DB: bootcamp2025
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGUSER: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ctf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bootcamp2025"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      

  nginx:
    build:
      context: ./nginx
      dockerfile: prod.Dockerfile
    container_name: ctf-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - ctf-network
    restart: always

volumes:
  postgres_data:

networks:
  ctf-network:
    external: true
