version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
    environment:
      - REACT_APP_API_URL=https://leftclicksec.org/api/v1
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: prod.dockerfile
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.4
    env_file:
      - ./.env.prod
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - ./db/mysql-files:/var/lib/mysql-files:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data: